services:
  backend:
    build:
      context: ./backend
    environment:
      DATABASE_HOST: db
      DATABASE_USER: ${POSTGRES_USER}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD}
      DATABASE_DATABASE: ${POSTGRES_DB}
      DATABASE_DRIVER: ${DATABASE_DRIVER}
      BACKEND_DOMAIN: ${BACKEND_DOMAIN}
      LOGTO_PUBLIC_DOMAIN: ${LOGTO_PUBLIC_DOMAIN}
      LOGTO_ENDPOINT_INTERNAL: ${LOGTO_ENDPOINT_INTERNAL}
      IMAGESTORE_DB_PATH: ${IMAGESTORE_DB_PATH}
    ports:
      - "${BACKEND_PORT}:8000"
    depends_on:
      db-init:
        condition: service_completed_successfully
    volumes:
      - imagestore-db:${IMAGESTORE_DB_PATH}:ro
    networks:
      - db-network

  db:
    image: postgres:16.14-alpine3.23
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

      LOGTO_DB_USER: ${LOGTO_DB_USER}
      LOGTO_DB_PASSWORD: ${LOGTO_DB_PASSWORD}
      LOGTO_DB: ${LOGTO_DB}
    
    ports:
      - "5432:5432"

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - db-network

    volumes:
      - db-data:/var/lib/postgresql/data

  db-init:
    image: postgres:16.14-alpine3.23
    environment:
      DB_HOST: db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      LOGTO_DB_USER: ${LOGTO_DB_USER}
      LOGTO_DB_PASSWORD: ${LOGTO_DB_PASSWORD}
      LOGTO_DB: ${LOGTO_DB}
    volumes:
      - ./logto/init-logto-db.sh:/init-logto-db.sh:ro
    command: [ "sh", "/init-logto-db.sh" ]
    networks:
      - db-network
    depends_on:
      db:
        condition: service_healthy

  logto:
    image: ghcr.io/logto-io/logto:latest
    depends_on:
      db-init:
        condition: service_completed_successfully
    ports:
      - "${LOGTO_PUBLIC_PORT}:3001"
      - "${LOGTO_ADMIN_PORT}:3002"
    environment:
      DB_URL: postgres://${LOGTO_DB_USER}:${LOGTO_DB_PASSWORD}@db:5432/${LOGTO_DB}
      ENDPOINT: ${LOGTO_PUBLIC_DOMAIN}
      ADMIN_ENDPOINT: ${LOGTO_ADMIN_DOMAIN}
      TRUST_PROXY_HEADER: "1"
    
    volumes:
      - ./logto/start.sh:/start.sh:ro
    entrypoint: ["/bin/sh", "/start.sh"]
    networks:
      - db-network
  
  init_logto:
    build:
      context: ./logto/init-logto
    depends_on:
      logto:
        condition: service_started
    
    environment:
      LOGTO_ENDPOINT: ${LOGTO_ENDPOINT_INTERNAL}
      LOGTO_MANAGEMENT_API_RESOURCE: ${LOGTO_MANAGEMENT_API_RESOURCE}
      LOGTO_M2M_APP_ID: ${LOGTO_M2M_APP_ID}
      LOGTO_M2M_APP_SECRET: ${LOGTO_M2M_APP_SECRET}
      APP_NAME: ${APP_NAME}
      APP_TYPE: ${APP_TYPE}
      APP_REDIRECT_URI: ${APP_REDIRECT_URI}
      APP_POST_LOGOUT_REDIRECT_URI: ${FRONTEND_DOMAIN} 
      APP_CORS_ORIGIN: ${FRONTEND_DOMAIN}
      BACKEND_DOMAIN: ${BACKEND_DOMAIN}
    networks:
      - db-network
  
  frontend:
    build: 
      context: ./frontend
    environment:
      VITE_LOGTO_ENDPOINT: ${LOGTO_PUBLIC_DOMAIN}
      VITE_LOGTO_APP_ID: ${VITE_LOGTO_APP_ID}
      VITE_APP_URL: ${FRONTEND_DOMAIN}
      VITE_BACKEND_DOMAIN: ${BACKEND_DOMAIN}
    ports:
      - "${FRONTEND_PORT}:80"

networks:
  db-network:
    driver: bridge

volumes:
  db-data:
  imagestore-db:
