services:
  devcontainer:
    build:
      dockerfile: .devcontainer/Dockerfile

    volumes:
      - .:/workspaces/services:cached

    command: sleep infinity
    networks:
      - devcontainer-network

  logto:
    networks:
      - devcontainer-network
    
  frontend:
    networks:
      - devcontainer-network
  
  backend:

    networks:
      - devcontainer-network
    volumes:
      - ./backend/src:/app/src
      
    environment:
      - PYTHONPATH=/app/src:/app/.venv/lib/python3.12/site-packages
    command: python -m uvicorn backend.app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/src

  db:
    networks:
      - devcontainer-network
    
  garage:
    networks:
      - devcontainer-network

    ports:
      - 3902:3902

networks:
  devcontainer-network:
    driver: bridge