name: Push Docker Images

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  push:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Push images
        run: |
          docker compose push
