import os
from dotenv import load_dotenv

load_dotenv()

DATABASE_HOST = os.getenv("DATABASE_HOST")
DATABASE_USER = os.getenv("DATABASE_USER")
DATABASE_PASSWORD = os.getenv("DATABASE_PASSWORD")
DATABASE_DATABASE = os.getenv("DATABASE_DATABASE")
DATABASE_DRIVER = os.getenv("DATABASE_DRIVER")
BACKEND_DOMAIN = os.getenv("BACKEND_DOMAIN")
LOGTO_PUBLIC_DOMAIN = os.getenv("LOGTO_PUBLIC_DOMAIN")
LOGTO_ENDPOINT_INTERNAL = os.getenv("LOGTO_ENDPOINT_INTERNAL")

